# Generated by Django 4.1.3 on 2022-11-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=16)),
                ('profilepic', models.ImageField(upload_to='profilepics')),
                ('background_image', models.ImageField(upload_to='backgrounds/')),
                ('short_intro', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('CV', models.FileField(blank=True, null=True, upload_to='')),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('github', models.CharField(max_length=555)),
                ('linkedin', models.CharField(max_length=555)),
                ('instagram', models.CharField(max_length=555)),
                ('twitter', models.CharField(max_length=555)),
                ('facebook', models.CharField(max_length=555)),
                ('skills', models.ManyToManyField(blank=True, to='index.skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('content_image', models.ImageField(upload_to='content/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.profile')),
            ],
        ),
    ]
