# Generated by Django 4.1.3 on 2023-01-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='github',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
    ]
