# Generated by Django 4.1.3 on 2023-01-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_posts_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='content/')),
            ],
        ),
    ]
