# Generated by Django 4.1.3 on 2023-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_image_project_alter_posts_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
