# Generated by Django 4.1.3 on 2023-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_posts_content_image_posts_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content_image',
            field=models.ManyToManyField(blank=True, to='index.image'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='github',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
